# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
- name: Ponicode Unit Test
  # You may pin to the exact commit or the version.
  # uses: ponicode/unit-testing-action@dcb3d0d0e21d55a63f3bd58fa5f9aaa7ec447f52
  uses: ponicode/unit-testing-action@0.2.0
  with:
    # String: URL of the repo to be processed
    repoUrl: 
    # String: Ponicode UT user token from Github Secrets
    ponicodeUtToken: 
    # GitHub token to generate some comments into the PR
    githubToken: 
    # String[]: List of the files updated in the PR
    impactedFiles: 
    # String: branch on which the PR applies
    branch: # default is master
    # Comment the generated UT
    commentUTs: 
